[package]
name = "pb-auth-telegram"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.10", features = ["macros", "auto-send"] }
tokio = { version = "1", features = ["full"] }
dptree = "0.3"
jsonwebtoken = "8"
serde = {version = "1.0", features = ["derive"] }
