name: Build and test (auth bot)

on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
            
    - name: Build
      run: cargo build --verbose
      working-directory: ./pb-auth-telegram

    - name: Run tests
      run: cargo test --verbose
      working-directory: ./pb-auth-telegram

    - name: Verify formatting
      run: cargo fmt --all -- --verbose --check
      working-directory: ./pb-auth-telegram
